insert into thuyntb.DB_BTS_THANG (THANG, MA_BTS, TEN_BTS, TINH, QUAN, NHOM, PHUONG, DIA_CHI, TTVT, TTVT_ID, NGAY_HD, 
NGAY_CN, TRANGTHAI, NGAY_OFF_TRAM, BTS_ID, MA_NV, PHUONG_ID, QUAN_ID, PBHKV_ID, MA_PB_BTS, TEN_PBH_KODAU, 
TEN_PHUONG_KD, GHI_CHU, CUAHANG_ID)
SELECT 202306,a.ma_bts, a.ten_bts, a.tinh, a.quan, a.nhom, a.phuong, a.dia_chi,
       a.ttvt, a.ttvt_id, a.ngay_hd, a.ngay_cn, a.trangthai,
       a.ngay_off_tram,  a.bts_id, a.ma_nv,
       a.phuong_id, a.quan_id, a.pbhkv_id, b.ma_pb, b.ten_pbh_kodau, a.ten_phuong_kd, a.ghi_chu,
       a.cuahang_id
  FROM ttkdhcm_ktnv.db_bts@dhsxkd a,ttkdhcm_ktnv.dm_phongbh@dhsxkd b 
where a.pbhkv_id=b.pbh_ql_id(+);

select * from thuyntb.DB_BTS_THANG
where ma_bts = 'TESTERICC30H' 
where thang = 202307   1364764
select * from VINATT.TIEUDUNG_BTS_202307_KIEUMOI
where bts_name is null

WITH 
CTE AS(
SELECT A.*, CASE WHEN INSTR(BTS_NAME, '_') = 0 AND INSTR(BTS_NAME, '-') > 0
                    THEN UPPER(SUBSTR(BTS_NAME, INSTR(BTS_NAME, '-') + 1, 6))
                 WHEN INSTR(BTS_NAME, '-') = 0 AND INSTR(BTS_NAME, '_') > 0
                    THEN UPPER(SUBSTR(BTS_NAME, INSTR(BTS_NAME, '_') + 1, 6))
                 END BTS_CODE 
FROM VINATT.TIEUDUNG_BTS_202212_KIEUMOI A
),
CTE2 AS(
SELECT TEN_PBH_KODAU, SUBSCRIBER_ID FROM CTE A LEFT JOIN thuyntb.DB_BTS_THANG B ON A.BTS_CODE = B.MA_BTS
WHERE THANG = '202307'
)
SELECT CTE2.TEN_PBH_KODAU, COUNT(CTE.SUBSCRIBER_ID) FROM CTE LEFT JOIN CTE2 ON CTE.SUBSCRIBER_ID = CTE2.SUBSCRIBER_ID
GROUP BY CTE2.TEN_PBH_KODAU

SELECT * FROM VINATT.TIEUDUNG_BTS_202307_KIEUMOI
SELECT * FROM CUOCVINA.HCM_KPI_VINAPHONE_202307          --1357350
WHERE ACCS_MTHD_KEY in ( '84941867321','84941917218')

84522475526
84921036947
84941866130
84926586075
84528346550
84942946431

SELECT SUBSCRIBER_ID, COUNT(SUBSCRIBER_ID) FROM VINATT.TIEUDUNG_BTS_202307_KIEUMOI
GROUP BY SUBSCRIBER_ID
HAVING COUNT(SUBSCRIBER_ID) > 1;

WITH 
TIEUDUNG AS(
SELECT A.*, '84'||SUBSCRIBER_ID AS SDT FROM VINATT.TIEUDUNG_BTS_202307_KIEUMOI A
),
CUOCVINA AS(
SELECT * 
FROM (
    SELECT ACCS_MTHD_KEY, SO_IMEI, LOAI_TB, NGAY_HUY_CUA_THUEBAO_HUY, 
        ROW_NUMBER() OVER(PARTITION BY ACCS_MTHD_KEY ORDER BY NGAY_HUY_CUA_THUEBAO_HUY) RA
    FROM CUOCVINA.HCM_KPI_VINAPHONE_202307 
    WHERE SO_IMEI IS NOT NULL AND LOAI_TB = 1
    )
WHERE RA = 1
),
COUNT_IMEI AS(
SELECT SO_IMEI, COUNT(SDT) FROM TIEUDUNG A 
    LEFT JOIN CUOCVINA B ON A.SDT = B.ACCS_MTHD_KEY
GROUP BY SO_IMEI
HAVING COUNT(SDT)>=3
)
SELECT A.*, B.SO_IMEI, C.SO_IMEI AS CHECK_IMEI FROM TIEUDUNG A 
    LEFT JOIN CUOCVINA B ON A.SDT = B.ACCS_MTHD_KEY
    LEFT JOIN COUNT_IMEI C ON B.SO_IMEI = C.SO_IMEI
WHERE C.SO_IMEI IS NOT NULL 
    AND A.VOICE_ONNET_OG_USG + A.VOICE_OFFNET_OG_USG + A.VOICE_ONNET_IC_USG + A.VOICE_OFFNET_IC_USG < 10
    AND A.DATA_USG < 102400 AND A.RCHRG_AMT < 5000
;

WITH GROUP_DEVICE AS(
SELECT * 
FROM(
    SELECT HNDST_MDL_CD, COUNT(HNDST_MDL_CD) AS DEM
    FROM VINATT.TIEUDUNG_BTS_202307_KIEUMOI
    GROUP BY HNDST_MDL_CD
    ORDER BY COUNT(HNDST_MDL_CD) DESC
)
WHERE UPPER(HNDST_MDL_CD) LIKE '%QUECTEL%'
),
DEVIDE AS(
SELECT BRAND_NAME, DONG_MAY, PRIMARY_HARDWARE_TYPE
FROM THUYNTB.IOT
GROUP BY BRAND_NAME, DONG_MAY, PRIMARY_HARDWARE_TYPE
SELECT * FROM GROUP_DEVICE A LEFT JOIN THUYNTB.IOT B ON A.HNDST_MDL_CD = B.DONG_MAY
ORDER BY HNDST_MDL_CD;

--QUECTEL + SPAM
SELECT * FROM VINATT.TIEUDUNG_BTS_202307_KIEUMOI
WHERE UPPER(HNDST_MDL_CD) LIKE '%QUECTEL%'
    AND TO_NUMBER(REPLACE(TKC_CALL, '.', ',')) = 0
    AND TO_NUMBER(REPLACE(TKC_DATA, '.', ',')) = 0
    AND TO_NUMBER(REPLACE(TKC_OTHER, '.', ',')) = 0
    AND TO_NUMBER(REPLACE(TKC_SMS, '.', ',')) > 0;

--T?p khách hàng du l?ch
WITH TIEUDUNG AS(
SELECT A.*, '84'||SUBSCRIBER_ID AS SDT FROM VINATT.TIEUDUNG_BTS_202307_KIEUMOI A
)
SELECT *       
FROM TIEUDUNG A LEFT JOIN THUYNTB.ID430_DULICH B ON A.SDT = B.SUBSCRIBER_ID
WHERE B.SUBSCRIBER_ID IS NOT NULL;

--T?p KH không ?n ??nh HCM
WITH PHONE_YEAR AS(
SELECT SUBSCRIBER_ID FROM VINATT.TIEUDUNG_BTS_202201_KIEUMOI
UNION ALL
SELECT SUBSCRIBER_ID FROM VINATT.TIEUDUNG_BTS_202202_KIEUMOI
UNION ALL
SELECT SUBSCRIBER_ID FROM VINATT.TIEUDUNG_BTS_202203_KIEUMOI
UNION ALL
SELECT SUBSCRIBER_ID FROM VINATT.TIEUDUNG_BTS_202204_KIEUMOI
UNION ALL
SELECT SUBSCRIBER_ID FROM VINATT.TIEUDUNG_BTS_202205_KIEUMOI
UNION ALL
SELECT SUBSCRIBER_ID FROM VINATT.TIEUDUNG_BTS_202206_KIEUMOI
UNION ALL
SELECT SUBSCRIBER_ID FROM VINATT.TIEUDUNG_BTS_202207_KIEUMOI
UNION ALL
SELECT SUBSCRIBER_ID FROM VINATT.TIEUDUNG_BTS_202208_KIEUMOI
UNION ALL
SELECT SUBSCRIBER_ID FROM VINATT.TIEUDUNG_BTS_202209_KIEUMOI
UNION ALL
SELECT SUBSCRIBER_ID FROM VINATT.TIEUDUNG_BTS_202210_KIEUMOI
UNION ALL
SELECT SUBSCRIBER_ID FROM VINATT.TIEUDUNG_BTS_202211_KIEUMOI
UNION ALL
SELECT SUBSCRIBER_ID FROM VINATT.TIEUDUNG_BTS_202212_KIEUMOI
)
SELECT SUBSCRIBER_ID, COUNT(SUBSCRIBER_ID)
FROM PHONE_YEAR 
GROUP BY SUBSCRIBER_ID
HAVING COUNT(SUBSCRIBER_ID) <= 5;

--T?p khóa h?y
SELECT * FROM VINATT.TIEUDUNG_BTS_202212_KIEUMOI     
WHERE LIFE_CYCLE_STAT_CD IN ('K1C', 'K2C', 'CAN')


--T?p không PSC : kh?i làm

---------KH?N C?P - QUAN TR?NG --------------
--1.TB chu?n b? khóa 1C và có nhi?u ngày không b?t máy.
SELECT * FROM VINATT.TIEUDUNG_BTS_202212_KIEUMOI  
SELECT * FROM CUOCVINA.HCM_KPI_VINAPHONE_202212
EFF_TO_DT ;

SELECT * FROM VINATT.TIEUDUNG_BTS_202212_KIEUMOI
WHERE ACCT_EXPIRE_DATE < DATE '2023-01-01';

--2.Thue bao khong goi phat sinh luong luu data
SELECT * FROM VINATT.TIEUDUNG_BTS_202211_KIEUMOI A 
    JOIN VINATT.TIEUDUNG_BTS_202212_KIEUMOI B ON A.SUBSCRIBER_ID = B.SUBSCRIBER_ID
WHERE TO_NUMBER(A.DATA_USG) = 0
    AND TO_NUMBER(B.DATA_USG) >= 500*1024
    AND B.SERVICE_ID IS NULL
    AND B.GOI_KMCB_SU_DUNG IS NULL

--3.TB khong goi phat sinh TKC tang dot bien
WITH ALL_DATA AS(
SELECT SUBSCRIBER_ID, SERVICE_ID, GOI_KMCB_SU_DUNG, TOTAL_TKC, ACCT_EXPIRE_DATE, 202212 AS THANG FROM VINATT.TIEUDUNG_BTS_202212_KIEUMOI
UNION ALL
SELECT SUBSCRIBER_ID, SERVICE_ID, GOI_KMCB_SU_DUNG, TOTAL_TKC, ACCT_EXPIRE_DATE, 202206 AS THANG FROM VINATT.TIEUDUNG_BTS_202206_KIEUMOI
UNION ALL
SELECT SUBSCRIBER_ID, SERVICE_ID, GOI_KMCB_SU_DUNG, TOTAL_TKC, ACCT_EXPIRE_DATE, 202207 AS THANG FROM VINATT.TIEUDUNG_BTS_202207_KIEUMOI
UNION ALL
SELECT SUBSCRIBER_ID, SERVICE_ID, GOI_KMCB_SU_DUNG, TOTAL_TKC, ACCT_EXPIRE_DATE, 202208 AS THANG FROM VINATT.TIEUDUNG_BTS_202208_KIEUMOI
UNION ALL
SELECT SUBSCRIBER_ID, SERVICE_ID, GOI_KMCB_SU_DUNG, TOTAL_TKC, ACCT_EXPIRE_DATE, 202209 AS THANG FROM VINATT.TIEUDUNG_BTS_202209_KIEUMOI
UNION ALL
SELECT SUBSCRIBER_ID, SERVICE_ID, GOI_KMCB_SU_DUNG, TOTAL_TKC, ACCT_EXPIRE_DATE, 202210 AS THANG FROM VINATT.TIEUDUNG_BTS_202210_KIEUMOI
UNION ALL
SELECT SUBSCRIBER_ID, SERVICE_ID, GOI_KMCB_SU_DUNG, TOTAL_TKC, ACCT_EXPIRE_DATE, 202211 AS THANG FROM VINATT.TIEUDUNG_BTS_202211_KIEUMOI
) SELECT * FROM VINATT.TIEUDUNG_BTS_202209_KIEUMOI
SELECT * FROM VINATT.TIEUDUNG_BTS_202212_KIEUMOI
SELECT A.*, LAG(TOTAL_TKC, 1, 0) OVER(PARTITION BY SUBSCRIBER_ID ORDER BY THANG) AS LAG_TKC 
FROM ALL_DATA A
SELECT * FROM VINATT.TIEUDUNG_BTS_202212_KIEUMOI LEFT JOIN ;

--DAY MOI CHUAN AL SO 3 
SELECT A.*
FROM VINATT.TIEUDUNG_BTS_202212_KIEUMOI A
    LEFT JOIN VINATT.TIEUDUNG_BTS_202211_KIEUMOI A1 ON A.SUBSCRIBER_ID = A1.SUBSCRIBER_ID
    LEFT JOIN VINATT.TIEUDUNG_BTS_202210_KIEUMOI A2 ON A.SUBSCRIBER_ID = A2.SUBSCRIBER_ID
    LEFT JOIN VINATT.TIEUDUNG_BTS_202209_KIEUMOI A3 ON A.SUBSCRIBER_ID = A3.SUBSCRIBER_ID
    LEFT JOIN VINATT.TIEUDUNG_BTS_202208_KIEUMOI A4 ON A.SUBSCRIBER_ID = A4.SUBSCRIBER_ID
WHERE A.GOI_KMCB_SU_DUNG IS NULL
    AND A1.GOI_KMCB_SU_DUNG IS NULL
    AND A2.MORE_COL2 IS NULL
    AND A3.MORE_COL2 IS NULL
    AND A4.MORE_COL2 IS NULL
    AND TO_NUMBER(REPLACE(A.TOTAL_TKC, '.', ',')) - TO_NUMBER(REPLACE(A1.TOTAL_TKC, '.', ',')) > 50000;
    
--TB có gói và TD l?u l??ng tho?i DATA SMS trong gói th?p
WITH PHONE_YEAR AS(
SELECT SUBSCRIBER_ID FROM VINATT.TIEUDUNG_BTS_202201_KIEUMOI
UNION ALL
SELECT SUBSCRIBER_ID FROM VINATT.TIEUDUNG_BTS_202202_KIEUMOI
UNION ALL
SELECT SUBSCRIBER_ID FROM VINATT.TIEUDUNG_BTS_202203_KIEUMOI
UNION ALL
SELECT SUBSCRIBER_ID FROM VINATT.TIEUDUNG_BTS_202204_KIEUMOI
UNION ALL
SELECT SUBSCRIBER_ID FROM VINATT.TIEUDUNG_BTS_202205_KIEUMOI
UNION ALL
SELECT SUBSCRIBER_ID FROM VINATT.TIEUDUNG_BTS_202206_KIEUMOI
UNION ALL
SELECT SUBSCRIBER_ID FROM VINATT.TIEUDUNG_BTS_202207_KIEUMOI
UNION ALL
SELECT SUBSCRIBER_ID FROM VINATT.TIEUDUNG_BTS_202208_KIEUMOI
UNION ALL
SELECT SUBSCRIBER_ID FROM VINATT.TIEUDUNG_BTS_202209_KIEUMOI
UNION ALL
SELECT SUBSCRIBER_ID FROM VINATT.TIEUDUNG_BTS_202210_KIEUMOI
UNION ALL
SELECT SUBSCRIBER_ID FROM VINATT.TIEUDUNG_BTS_202211_KIEUMOI
UNION ALL
SELECT SUBSCRIBER_ID, GOI_KMCB_SU_DUNG, SERVICE_ID FROM VINATT.TIEUDUNG_BTS_202212_KIEUMOI
)
SELECT SUBSCRIBER_ID, COUNT(SUBSCRIBER_ID)
FROM PHONE_YEAR 
GROUP BY SUBSCRIBER_ID
HAVING COUNT(SUBSCRIBER_ID) <= 5;

SELECT * ;

--6.TB suy gi?m tieu dung luu luong hoac tb dung tieudung dot ngot
WITH TIEUDUNG AS(
SELECT A.SUBSCRIBER_ID, A.TOTAL_TKC, A.TOTAL_CALL, A.TOTAL_SMS, A.TOTAL_DATA, A.ACCT_EXPIRE_DATE, 
    B.TOTAL_CALL AS BCALL, B.TOTAL_SMS AS BSMS, B.TOTAL_DATA AS BDATA, 
    C.TOTAL_CALL AS CCALL, C.TOTAL_SMS AS CSMS, C.TOTAL_DATA AS CDATA, 
    D.TOTAL_CALL AS DCALL, D.TOTAL_SMS AS DSMS, D.TOTAL_DATA AS DDATA
FROM VINATT.TIEUDUNG_BTS_202212_KIEUMOI A
    JOIN VINATT.TIEUDUNG_BTS_202209_KIEUMOI B ON A.SUBSCRIBER_ID = B.SUBSCRIBER_ID 
    JOIN VINATT.TIEUDUNG_BTS_202210_KIEUMOI C ON A.SUBSCRIBER_ID = C.SUBSCRIBER_ID 
    JOIN VINATT.TIEUDUNG_BTS_202211_KIEUMOI D ON A.SUBSCRIBER_ID = D.SUBSCRIBER_ID 
) 
SELECT A.*
FROM TIEUDUNG A
WHERE (TO_NUMBER(REPLACE(TOTAL_CALL, '.',','))*2 < TO_NUMBER(REPLACE(BCALL, '.',',')) AND TO_NUMBER(REPLACE(BCALL, '.',','))*2 < TO_NUMBER(REPLACE(CCALL, '.',',')))
    OR (TO_NUMBER(REPLACE(TOTAL_SMS, '.',','))*2 < TO_NUMBER(REPLACE(BSMS, '.',',')) AND TO_NUMBER(REPLACE(BSMS, '.',','))*2 < TO_NUMBER(REPLACE(CSMS, '.',',')))
    OR (TO_NUMBER(REPLACE(TOTAL_DATA, '.',','))*2 < TO_NUMBER(REPLACE(BDATA, '.',',')) AND TO_NUMBER(REPLACE(BDATA, '.',','))*2 < TO_NUMBER(REPLACE(CDATA, '.',',')))
;

--TB co hanh vi su dung sim thay the
WITH 
TIEUDUNG AS(
SELECT A.*, '84'||SUBSCRIBER_ID AS SDT FROM VINATT.TIEUDUNG_BTS_202307_KIEUMOI A
),
CUOCVINA AS(
SELECT * 
FROM (
    SELECT ACCS_MTHD_KEY, SO_IMEI, LOAI_TB, NGAY_HUY_CUA_THUEBAO_HUY, 
        ROW_NUMBER() OVER(PARTITION BY ACCS_MTHD_KEY ORDER BY NGAY_HUY_CUA_THUEBAO_HUY) RA
    FROM CUOCVINA.HCM_KPI_VINAPHONE_202307 
    WHERE SO_IMEI IS NOT NULL AND LOAI_TB = 1
    )
WHERE RA = 1
)
SELECT A.*, ROW_NUMBER() OVER(PARTITION BY SO_IMEI ORDER BY SO_EMEI) AS  
FROM TIEUDUNG A
    LEFT JOIN CUOCVINA B ON A.SUBSCRIBER_ID = B.ACCS_MTHD_KEY
GROUP BY SO_EMEI;

WITH 
TIEUDUNG AS(
SELECT A.*, '84'||SUBSCRIBER_ID AS SDT FROM VINATT.TIEUDUNG_BTS_202307_KIEUMOI A
),
CUOCVINA AS(
SELECT * 
FROM (
    SELECT ACCS_MTHD_KEY, SO_IMEI, LOAI_TB, NGAY_HUY_CUA_THUEBAO_HUY, 
        ROW_NUMBER() OVER(PARTITION BY ACCS_MTHD_KEY ORDER BY NGAY_HUY_CUA_THUEBAO_HUY) RA
    FROM CUOCVINA.HCM_KPI_VINAPHONE_202307 
    WHERE SO_IMEI IS NOT NULL AND LOAI_TB = 1
    )
WHERE RA = 1
),
COUNT_IMEI AS(
SELECT SO_IMEI, COUNT(SDT) FROM TIEUDUNG A 
    LEFT JOIN CUOCVINA B ON A.SDT = B.ACCS_MTHD_KEY
GROUP BY SO_IMEI
HAVING COUNT(SDT)>=3
)
SELECT A.*, B.SO_IMEI, C.SO_IMEI AS CHECK_IMEI FROM TIEUDUNG A 
    LEFT JOIN CUOCVINA B ON A.SDT = B.ACCS_MTHD_KEY
    LEFT JOIN COUNT_IMEI C ON B.SO_IMEI = C.SO_IMEI
WHERE C.SO_IMEI IS NOT NULL 
;

--Khan cap, quan trong
SELECT * FROM B.SO)IMEI CHECK_IMEI FROM TIEUDUNG A 
    LEFT JOIN CUOCVINA ON SDT = B.ACCS_MTH_KEY
    LEFT JOINT COUNT_IMEI C ON V.SO_IMEI = SO_IEMI
WHERE SO_IMEI IS NOT NULL

--KHAN CAP - QUAN TRONG --THIEU THUOC TAP NGUY CO
SELECT * 
FROM VINATT.TIEUDUNG_BTS_202212_KIEUMOI 
WHERE HNDST_MDL_TYP_CD IN ('3G', '4G', '5G', '6G') 
    AND TO_NUMBER(REPLACE(TKC_DATA, '.',',')) > 0
    AND TO_NUMBER(REPLACE(TOTAL_TKC, '.',',')) > 100000
    AND (SERVICE_ID IS NOT NULL OR GOI_KMCB_SU_DUNG IS NOT NULL)
  
SELECT * FROM THUYNTB.GOI_TONGHOP_202212
--QUAN TRONG - KHONG KHAN CAP
WITH GOICUOC AS(
SELECT GOI_CUOC, CHUKY_ FROM THUYNTB.GOI_TONGHOP_202212
)
SELECT *
FROM VINATT.TIEUDUNG_BTS_202212_KIEUMOI 
WHERE 
    